import type { SplashBanner, SplashPortrait } from "../types/atmosphereConfig";

export const splashPortraits: SplashPortrait[] = [
	{
		id: "jett",
		name: "捷风",
		badge: "默认",
		image: "/assets/images/splash/portraits/jett.webp",
		ultName: "飓刃",
		ultLine: "看招！",
	},
	{
		id: "kayo",
		name: "K/O",
		image: "/assets/images/splash/portraits/kayo.webp",
		ultName: "无效命令",
		ultLine: "无路可逃！",
	},
	{
		id: "phoenix",
		name: "不死鸟",
		image: "/assets/images/splash/portraits/phoenix.webp",
		ultName: "再火一回",
		ultLine: "来吧，走起！",
	},
	{
		id: "iso",
		name: "壹决",
		image: "/assets/images/splash/portraits/iso.webp",
		ultName: "决斗通牒",
		ultLine: "拔枪吧！就你和我！",
	},
	{
		id: "yoru",
		name: "夜露",
		image: "/assets/images/splash/portraits/yoru.webp",
		ultName: "神鬼不觉",
		ultLine: "交给我了！",
	},
	{
		id: "killjoy",
		name: "奇乐",
		image: "/assets/images/splash/portraits/killjoy.webp",
		ultName: "全面封锁",
		ultLine: "倒计时开始！",
	},
	{
		id: "chamber",
		name: "尚勃勒",
		image: "/assets/images/splash/portraits/chamber.webp",
		ultName: "孤高火力",
		ultLine: "他们走不了了！",
	},
	{
		id: "waylay",
		name: "幻棱",
		image: "/assets/images/splash/portraits/waylay.webp",
		ultName: "时光修罗场",
		ultLine: "一息，一闪，一念！",
	},
	{
		id: "omen",
		name: "幽影",
		image: "/assets/images/splash/portraits/omen.webp",
		ultName: "离魂",
		ultLine: "我，无所不在！",
	},
	{
		id: "skye",
		name: "斯凯",
		image: "/assets/images/splash/portraits/skye.webp",
		ultName: "追猎之灵",
		ultLine: "把他们找出来！",
	},
	{
		id: "astra",
		name: "星礈",
		image: "/assets/images/splash/portraits/astra.webp",
		ultName: "星界形态",
		ultLine: "世界分裂！",
	},
	{
		id: "clove",
		name: "暮蝶",
		image: "/assets/images/splash/portraits/clove.webp",
		ultName: "化蝶",
		ultLine: "我回来了！",
	},
	{
		id: "harbor",
		name: "海神",
		image: "/assets/images/splash/portraits/harbor.webp",
		ultName: "怒涛",
		ultLine: "看我力挽狂澜！",
	},
	{
		id: "brimstone",
		name: "炼狱",
		image: "/assets/images/splash/portraits/brimstone.webp",
		ultName: "天基光束",
		ultLine: "天火降临！",
	},
	{
		id: "sova",
		name: "猎枭",
		image: "/assets/images/splash/portraits/sova.webp",
		ultName: "狂猎之怒",
		ultLine: "我，是猎人！",
	},
	{
		id: "gekko",
		name: "盖可",
		image: "/assets/images/splash/portraits/gekko.webp",
		ultName: "无敌超鲨",
		ultLine: "就交给你了小伙计！",
	},
	{
		id: "veto",
		name: "禁灭",
		image: "/assets/images/splash/portraits/veto.webp",
		ultName: "完全进化",
		ultLine: "让一切都湮灭！",
	},
	{
		id: "vyse",
		name: "维斯",
		image: "/assets/images/splash/portraits/vyse.webp",
		ultName: "铁棘禁园",
		ultLine: "武器都给我交出来！",
	},
	{
		id: "reyna",
		name: "芮娜",
		image: "/assets/images/splash/portraits/reyna.webp",
		ultName: "女皇旨令",
		ultLine: "瑟瑟发抖吧！",
	},
	{
		id: "viper",
		name: "蝰蛇",
		image: "/assets/images/splash/portraits/viper.webp",
		ultName: "蝰腹",
		ultLine: "不要妨碍我！",
	},
	{
		id: "sage",
		name: "贤者",
		image: "/assets/images/splash/portraits/sage.webp",
		ultName: "再起",
		ultLine: "你的使命还没结束！",
	},
	{
		id: "miks",
		name: "迷核",
		image: "/assets/images/splash/portraits/miks.webp",
		ultName: "音脉强袭",
		ultLine: "聆听这个！",
	},
	{
		id: "tejo",
		name: "钛狐",
		image: "/assets/images/splash/portraits/tejo.webp",
		ultName: "末日审判",
		ultLine: "末日从天而降！",
	},
	{
		id: "deadlock",
		name: "钢锁",
		image: "/assets/images/splash/portraits/deadlock.webp",
		ultName: "断魂索道",
		ultLine: "哪里也去不了！",
	},
	{
		id: "breach",
		name: "铁臂",
		image: "/assets/images/splash/portraits/breach.webp",
		ultName: "惊雷卷地",
		ultLine: "老铁要上了！",
	},
	{
		id: "cypher",
		name: "零",
		image: "/assets/images/splash/portraits/cypher.webp",
		ultName: "神经取析",
		ultLine: "让我看看你们都藏哪了？",
	},
	{
		id: "raze",
		name: "雷兹",
		image: "/assets/images/splash/portraits/raze.webp",
		ultName: "晚安焰火",
		ultLine: "狂欢开始了！",
	},
	{
		id: "neon",
		name: "霓虹",
		image: "/assets/images/splash/portraits/neon.webp",
		ultName: "超限暴走",
		ultLine: "好戏开始了！",
	},
	{
		id: "fade",
		name: "黑梦",
		image: "/assets/images/splash/portraits/fade.webp",
		ultName: "夜临",
		ultLine: "噩梦，吞噬他们！",
	},
];

export const splashMaps: SplashBanner[] = [
	{
		id: "ascent",
		name: "亚海悬城",
		image: "/assets/images/splash/banners/ascent.webp",
	},
	{
		id: "summit",
		name: "天枢云阙",
		image: "/assets/images/splash/banners/summit.webp",
	},
	{
		id: "abyss",
		name: "幽邃地窟",
		image: "/assets/images/splash/banners/abyss.webp",
	},
	{
		id: "breeze",
		name: "微风岛屿",
		image: "/assets/images/splash/banners/breeze.webp",
	},
	{
		id: "sunset",
		name: "日落之城",
		image: "/assets/images/splash/banners/sunset.webp",
	},
	{
		id: "icebox",
		name: "森寒冬港",
		image: "/assets/images/splash/banners/icebox.webp",
	},
	{
		id: "pearl",
		name: "深海明珠",
		image: "/assets/images/splash/banners/pearl.webp",
	},
	{
		id: "bind",
		name: "源工重镇",
		image: "/assets/images/splash/banners/bind.webp",
	},
	{
		id: "corrode",
		name: "盐海矿镇",
		image: "/assets/images/splash/banners/corrode.webp",
	},
	{
		id: "lotus",
		name: "莲华古城",
		image: "/assets/images/splash/banners/lotus.webp",
	},
	{
		id: "fracture",
		name: "裂变峡谷",
		image: "/assets/images/splash/banners/fracture.webp",
	},
	{
		id: "haven",
		name: "隐世修所",
		image: "/assets/images/splash/banners/haven.webp",
	},
	{
		id: "split",
		name: "霓虹町",
		image: "/assets/images/splash/banners/split.webp",
	},
];
