import type { SplashBanner, SplashPortrait } from "../types/atmosphereConfig";

export const splashPortraits: SplashPortrait[] = [
	{
		id: "jett",
		name: "捷风",
		badge: "默认",
		image: "/assets/images/splash/portraits/jett.webp",
		ultName: "飓刃",
		ultLines: ["看招！", "别挡我的路！"],
	},
	{
		id: "kayo",
		name: "K/O",
		image: "/assets/images/splash/portraits/kayo.webp",
		ultName: "无效命令",
		ultLines: ["你们，无路可逃！", "你，已被，剥夺力量！"],
	},
	{
		id: "phoenix",
		name: "不死鸟",
		image: "/assets/images/splash/portraits/phoenix.webp",
		ultName: "再火一回",
		ultLines: ["啊～来吧，走起！", "闹够了吗，该结束了！"],
	},
	{
		id: "iso",
		name: "壹决",
		image: "/assets/images/splash/portraits/iso.webp",
		ultName: "决斗通牒",
		ultLines: ["这是我的决斗！", "拔枪吧，就你和我！"],
	},
	{
		id: "yoru",
		name: "夜露",
		image: "/assets/images/splash/portraits/yoru.webp",
		ultName: "神鬼不觉",
		ultLines: ["交给我了！", "下一个是谁？"],
	},
	{
		id: "killjoy",
		name: "奇乐",
		image: "/assets/images/splash/portraits/killjoy.webp",
		ultName: "全面封锁",
		ultLines: ["倒计时开始！", "噢，你们快跑吧～"],
	},
	{
		id: "chamber",
		name: "尚勃勒",
		image: "/assets/images/splash/portraits/chamber.webp",
		ultName: "孤高火力",
		ultLines: ["他们走不了了！", "想玩是吧？我奉陪！"],
	},
	{
		id: "waylay",
		name: "幻棱",
		image: "/assets/images/splash/portraits/waylay.webp",
		ultName: "时光修罗场",
		ultLines: ["准备好，我上了！", "一息，一闪，一念！"],
	},
	{
		id: "omen",
		name: "幽影",
		image: "/assets/images/splash/portraits/omen.webp",
		ultName: "离魂",
		ultLines: ["他们将落荒而逃！", "离散！"],
	},
	{
		id: "skye",
		name: "斯凯",
		image: "/assets/images/splash/portraits/skye.webp",
		ultName: "追猎之灵",
		ultLines: ["把他们找出来！", "我找到你了！"],
	},
	{
		id: "astra",
		name: "星礈",
		image: "/assets/images/splash/portraits/astra.webp",
		ultName: "星界形态",
		ultLines: ["世界分裂！", "一分为二！"],
	},
	{
		id: "clove",
		name: "暮蝶",
		image: "/assets/images/splash/portraits/clove.webp",
		ultName: "化蝶",
		ultLines: ["我回来了，我就没走！", "你过瘾了，该轮到我了！"],
	},
	{
		id: "harbor",
		name: "海神",
		image: "/assets/images/splash/portraits/harbor.webp",
		ultName: "怒涛",
		ultLines: ["看我力挽狂澜！", "巨浪压顶！"],
	},
	{
		id: "brimstone",
		name: "炼狱",
		image: "/assets/images/splash/portraits/brimstone.webp",
		ultName: "天基光束",
		ultLines: ["天火降临！", "面对炼狱吧！"],
	},
	{
		id: "sova",
		name: "猎枭",
		image: "/assets/images/splash/portraits/sova.webp",
		ultName: "狂猎之怒",
		ultLines: ["我，是猎人！", "你无处可逃！"],
	},
	{
		id: "gekko",
		name: "盖可",
		image: "/assets/images/splash/portraits/gekko.webp",
		ultName: "无敌超鲨",
		ultLines: ["就交给你了小伙计！", "oh yeah，怪兽出击！"],
	},
	{
		id: "veto",
		name: "禁灭",
		image: "/assets/images/splash/portraits/veto.webp",
		ultName: "完全进化",
		ultLines: ["让一切都湮灭！", "来动一步试试！"],
	},
	{
		id: "vyse",
		name: "维斯",
		image: "/assets/images/splash/portraits/vyse.webp",
		ultName: "铁棘禁园",
		ultLines: ["武器！都交出来！", "适者，才配生存！"],
	},
	{
		id: "reyna",
		name: "芮娜",
		image: "/assets/images/splash/portraits/reyna.webp",
		ultName: "女皇旨令",
		ultLines: ["瑟瑟发抖吧！", "开始狩猎！"],
	},
	{
		id: "viper",
		name: "蝰蛇",
		image: "/assets/images/splash/portraits/viper.webp",
		ultName: "蝰腹",
		ultLines: ["不要妨碍我！", "爬过来受死！"],
	},
	{
		id: "sage",
		name: "贤者",
		image: "/assets/images/splash/portraits/sage.webp",
		ultName: "再起",
		ultLines: ["你的使命还没结束！", "浴血再战，矢志不移！"],
	},
	{
		id: "miks",
		name: "迷核",
		image: "/assets/images/splash/portraits/miks.webp",
		ultName: "音脉强袭",
		ultLines: ["就在这里，就是现在！", "聆听这个！"],
	},
	{
		id: "tejo",
		name: "钛狐",
		image: "/assets/images/splash/portraits/tejo.webp",
		ultName: "末日审判",
		ultLines: ["末日从天而降！", "来都来了，有种别走！"],
	},
	{
		id: "deadlock",
		name: "钢锁",
		image: "/assets/images/splash/portraits/deadlock.webp",
		ultName: "断魂索道",
		ultLines: ["把他们拖过来干掉！", "我的地盘，我说了算！"],
	},
	{
		id: "breach",
		name: "铁臂",
		image: "/assets/images/splash/portraits/breach.webp",
		ultName: "惊雷卷地",
		ultLines: ["统统给我上！", "摇起来！"],
	},
	{
		id: "cypher",
		name: "零",
		image: "/assets/images/splash/portraits/cypher.webp",
		ultName: "神经取析",
		ultLines: ["让我看看你们都藏哪了？", "我知道你们在哪！"],
	},
	{
		id: "raze",
		name: "雷兹",
		image: "/assets/images/splash/portraits/raze.webp",
		ultName: "晚安焰火",
		ultLines: ["一起狂欢！", "Fire in the hole！"],
	},
	{
		id: "neon",
		name: "霓虹",
		image: "/assets/images/splash/portraits/neon.webp",
		ultName: "超限暴走",
		ultLines: ["好戏开始了！", "嘿！你惹毛我了！"],
	},
	{
		id: "fade",
		name: "黑梦",
		image: "/assets/images/splash/portraits/fade.webp",
		ultName: "夜临",
		ultLines: ["永夜降临，噩梦开启！", "直面恐惧吧！"],
	},
];

export const splashMaps: SplashBanner[] = [
	{
		id: "ascent",
		name: "亚海悬城",
		image: "/assets/images/splash/banners/ascent.webp",
	},
	{
		id: "summit",
		name: "天枢云阙",
		image: "/assets/images/splash/banners/summit.webp",
	},
	{
		id: "abyss",
		name: "幽邃地窟",
		image: "/assets/images/splash/banners/abyss.webp",
	},
	{
		id: "breeze",
		name: "微风岛屿",
		image: "/assets/images/splash/banners/breeze.webp",
	},
	{
		id: "sunset",
		name: "日落之城",
		image: "/assets/images/splash/banners/sunset.webp",
	},
	{
		id: "icebox",
		name: "森寒冬港",
		image: "/assets/images/splash/banners/icebox.webp",
	},
	{
		id: "pearl",
		name: "深海明珠",
		image: "/assets/images/splash/banners/pearl.webp",
	},
	{
		id: "bind",
		name: "源工重镇",
		image: "/assets/images/splash/banners/bind.webp",
	},
	{
		id: "corrode",
		name: "盐海矿镇",
		image: "/assets/images/splash/banners/corrode.webp",
	},
	{
		id: "lotus",
		name: "莲华古城",
		image: "/assets/images/splash/banners/lotus.webp",
	},
	{
		id: "fracture",
		name: "裂变峡谷",
		image: "/assets/images/splash/banners/fracture.webp",
	},
	{
		id: "haven",
		name: "隐世修所",
		image: "/assets/images/splash/banners/haven.webp",
	},
	{
		id: "split",
		name: "霓虹町",
		image: "/assets/images/splash/banners/split.webp",
	},
];
